# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detector_contract/detector.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'detector_contract/detector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n detector_contract/detector.proto\x12\x0b\x64\x65tector.v1\"\xc1\x01\n\x0e\x44\x65tectionFrame\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\x1b\n\x13observed_at_unix_ms\x18\x03 \x01(\x03\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\x12\x0c\n\x04jpeg\x18\x06 \x01(\x0c\x12\x12\n\nsource_pts\x18\x07 \x01(\x03\x12\x15\n\rtime_base_num\x18\x08 \x01(\r\x12\x15\n\rtime_base_den\x18\t \x01(\r\"r\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x05 \x01(\r\x12\r\n\x05label\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"\xdc\x02\n\x0f\x44\x65tectionResult\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x04\x12\x1b\n\x13observed_at_unix_ms\x18\x03 \x01(\x03\x12\x1c\n\x14\x63ompleted_at_unix_ms\x18\x04 \x01(\x03\x12,\n\ndetections\x18\x05 \x03(\x0b\x32\x18.detector.v1.BoundingBox\x12\x15\n\rpreprocess_ms\x18\x06 \x01(\x02\x12\x14\n\x0cinference_ms\x18\x07 \x01(\x02\x12\x0e\n\x06nms_ms\x18\x08 \x01(\x02\x12%\n\x04\x63ode\x18\t \x01(\x0e\x32\x17.detector.v1.ResultCode\x12\x15\n\rerror_message\x18\n \x01(\t\x12\x12\n\nsource_pts\x18\x0b \x01(\x03\x12\x15\n\rtime_base_num\x18\x0c \x01(\r\x12\x15\n\rtime_base_den\x18\r \x01(\r*\x99\x01\n\nResultCode\x12\x1b\n\x17RESULT_CODE_UNSPECIFIED\x10\x00\x12\x12\n\x0eRESULT_CODE_OK\x10\x01\x12\x1d\n\x19RESULT_CODE_INVALID_FRAME\x10\x02\x12\x1a\n\x16RESULT_CODE_OVERLOADED\x10\x03\x12\x1f\n\x1bRESULT_CODE_INFERENCE_ERROR\x10\x04\x32S\n\x08\x44\x65tector\x12G\n\x06\x44\x65tect\x12\x1b.detector.v1.DetectionFrame\x1a\x1c.detector.v1.DetectionResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detector_contract.detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULTCODE']._serialized_start=713
  _globals['_RESULTCODE']._serialized_end=866
  _globals['_DETECTIONFRAME']._serialized_start=50
  _globals['_DETECTIONFRAME']._serialized_end=243
  _globals['_BOUNDINGBOX']._serialized_start=245
  _globals['_BOUNDINGBOX']._serialized_end=359
  _globals['_DETECTIONRESULT']._serialized_start=362
  _globals['_DETECTIONRESULT']._serialized_end=710
  _globals['_DETECTOR']._serialized_start=868
  _globals['_DETECTOR']._serialized_end=951
# @@protoc_insertion_point(module_scope)
